Release/v3.9.0 high mutation burden variant matches
bcgsc/pori_ipr_python pull request #116
Opened 2023-05-16 18:49 UTC by dustinbleile

2023-05-16 21:42 UTC, darenillas approved these changes

2023-05-17 18:18 UTC, elewis2 requested changes

2023-05-17 18:18 UTC, elewis2 commented on ipr/annotate.py
> +                except HTTPError:
might be better to be more specific in catching this error - maybe check error text and re-throw if it's not a parsing problem (I'm assuming that's what this is catching?)

2023-05-17 18:18 UTC, elewis2 commented on ipr/main.py
> +        except Exception as err:
is it possible to check if it's actually a parsing error?

2023-05-17 19:32 UTC, dustinbleile commented on ipr/main.py
> +        except Exception as err:
Could add a comment to log the error on tmb issues instead of stopping?

As it is probably minor error & not something we want to stop reporting for?

2023-05-17 21:57 UTC, elewis2 commented on ipr/main.py
> +        except Exception as err:
Yup, that sounds good to me.

2023-05-17 21:58 UTC, elewis2 approved these changes

2023-05-17 21:58 UTC, merged