GERO-241 - handle pandas.NA input as null and add null tests for GSC Report integration edge cases.
bcgsc/pori_ipr_python pull request #45
Opened 2021-07-29 23:47 UTC by dustinbleile

Add some tests for the edgecase null types found in integration testing.

2021-08-05 17:23 UTC, creisle commented
Rather than replacing the NA here it might make more sense to just do a single df.fillna('') before you create the JSON?

2021-08-05 17:33 UTC, creisle requested changes

2021-08-05 17:33 UTC, creisle commented on tests/test_inputs.py
> +NULLS = ['', None, np.nan, pd.NA]
It can be dangerous to assume '' is always a null value. We often use null to mean not given/specified or unknown but then sometimes '' is the actual value. For example the untemplated sequence between breakpoints in a structural variant or the ref/alt seq in a small mutation

2021-08-05 17:33 UTC, creisle commented on tests/test_inputs.py
> +    def test_load_small_mutations_probe(self) -> None:
I think i must be missing something here. Why is this test indented and given the self argument? it does not appear to be part of a class

2021-08-06 00:44 UTC, dustinbleile commented on tests/test_inputs.py
> +    def test_load_small_mutations_probe(self) -> None:
Part of 'class TestPreProcessSmallMutations:'
Code view just looks weird

2021-11-02 01:31 UTC, dustinbleile commented on tests/test_inputs.py
> +NULLS = ['', None, np.nan, pd.NA]
For the keys being tested here, I think all the NULLS are equivalent.
Maybe just a comment about some of the exceptions like the ref/alt seq?
Would you list of  exceptions?

2021-11-10 21:34 UTC, creisle commented on tests/test_inputs.py
> +NULLS = ['', None, np.nan, pd.NA]
ya, I would definitely put a comment about not using this for fields where empty string is valid, I might rename the variable to match but i can't think of anything other than `NON_EMPTY_STRING_NULLS` and that's a bit long so maybe just the comment for now unless you have a better name

2021-11-10 21:41 UTC, creisle commented on tests/test_inputs.py
> +        for kb_cat in list(INPUT_COPY_CATEGORIES.values()) + NULLS:
not blocking but might be nice to use parameterize here instead so that you can easily tell which case fails. If you stack the decorators it will do all combinations

```python
@pytest.mark.parameterize('kb_category', INPUT_COPY_CATEGORIES.values())
@pytest.mark.parameterize('column_name', COPY_OPTIONAL)
@pytest.mark.parameterize('null_value', NULLS)
def test_nulls(kb_category, column_name, null_value): 
    copy_var = {'gene': 'ERBB2', 'kbCategory': kb_category}
    copy_var[column_name] = null
    records = preprocess_copy_variants([copy_var])
    record = records[0]
    assert record['variantType'] == 'cnv'
```

2021-11-15 19:42 UTC, creisle approved these changes

2021-11-15 20:13 UTC, merged