Sdev 2789 germline key alterations
bcgsc/pori_ipr_python pull request #76
Opened 2022-05-13 22:41 UTC by dustinbleile

Adds new features for filtering matches to germline events and excluding matches from reporting.
SDEV-2789 / GERO-283

2022-05-16 15:21 UTC, dustinbleile commented
- TODO - this will probably need some additional tests & coverage to be accepted.

2022-05-16 15:26 UTC, dustinbleile commented on ipr/main.py
Note: main reason for match_germline and kb_match_filters in this file is to remove events before create_key_alterations makes the summary table and counts.

2022-05-17 22:05 UTC, creisle requested changes

2022-05-17 22:05 UTC, creisle commented on ipr/ipr.py
> +        elif kb_match['category'] in GERMLINE_BASE_TERMS:
Rather than changing the variant to be germline when the statement relevance implies it probably is, couldn't we just get the germline state from the variant itself?

2022-05-17 22:05 UTC, creisle commented on ipr/main.py
> +    if kb_match_filters:
Rather than passing a dictionary referring to specific filters, it might make more sense to just allow a "custom_kb_match_filter" function as an argument? then you would also not need 2 separate functions. It would also be more flexible for external users

2022-05-18 16:58 UTC, dustinbleile commented on ipr/ipr.py
> +        elif kb_match['category'] in GERMLINE_BASE_TERMS:
The details of these statement matches will be in the Germline section of the report, regardless of the status to the variant.

2022-05-18 17:40 UTC, dustinbleile commented on ipr/main.py
> +    if kb_match_filters:
I think germline_kb_matches might be a good one to just build in, because it needs variants as options too.  Seems like it might be common & not that intuitive.

Replacing the kb_match_filters confusing list of dicts with a custom_kb_match_filter function sounds like good like a good idea though.

A function that takes a kbMatch list and returns a filtered kbMatch list?

2022-05-18 19:11 UTC, dustinbleile commented on ipr/main.py
> +    if kb_match_filters:
If functions are passed as inputs, the input values used can no-longer be saved and loaded.

{noformat}
[I 220518 11:43:12 create_report:1560] Saving create_report input to /home/dbleile/gsc_genomic_report/tmp3/data/create_report_inputs.json
[E 220518 11:43:12 create_report:1616] Processing ABORTED at 2022-05-18 11:43:12: Object of type function is not JSON serializable
{noformat}

2022-05-18 19:15 UTC, creisle commented on ipr/main.py
> +    if kb_match_filters:
That code is outside of this adaptor right? The content dump should still be serialisable.

2022-05-31 21:23 UTC, dustinbleile commented on ipr/ipr.py
> +        elif kb_match['category'] in GERMLINE_BASE_TERMS:
Since the germline status of the variant is an optional detail, this summarized the type of match and that the full details will be under the 'Germline' section of the report.

2022-06-01 21:18 UTC, mattdoug604 approved these changes

2022-06-14 15:32 UTC, closed without merging