Release/v3.4.0
bcgsc/pori_ipr_python pull request #82
Opened 2022-07-19 18:48 UTC by elewis2

Release v3.4.0
New features:
- DEVSU-1845 - handle internalPancancer fields

2022-07-19 21:53 UTC, dustinbleile approved these changes

2022-07-19 21:56 UTC, creisle commented on ipr/content.spec.json
> +                            "expression (internal pancancer cohort)",
was the IPR logic changed for this already? why do we have a specific type here instead of the regular 1st, 2nd, third type

2022-07-20 16:14 UTC, elewis2 commented on ipr/content.spec.json
> +                            "expression (internal pancancer cohort)",
Yes, there are columns to display internal pancancer kiqr and percentile in the genomic report.

2022-07-20 16:29 UTC, elewis2 commented on ipr/content.spec.json
> +                            "expression (internal pancancer cohort)",
Is there a name you'd prefer in the display? "Internal pancancer" was agreed on as being project-agnostic, with the name of the actual cohort used to be displayed elsewhere

2022-07-20 21:59 UTC, creisle commented on ipr/content.spec.json
> +                            "expression (internal pancancer cohort)",
If the corresponding changes have already been made to IPR then just leave it as is for now. It can be changed at a later date if we find something better

2022-07-20 22:00 UTC, dustinbleile commented on ipr/content.spec.json
> +                            "expression (internal pancancer cohort)",
![image](https://user-images.githubusercontent.com/34173070/180088684-2e30c8f1-be04-46a3-a2b6-db05e01a5480.png)
These values are for under the 'Internal Pancancer' of the Expression tables, so the names make sense in context of the 'genomic' template, I think at least.

The only QC value used/displayed is the "expression (disease QC)"

These other QC values I would not know how to use, right now
```
"expression (primary site QC)",
"expression (biopsy site QC)",
"expression (internal pancancer cohort QC)"
```

2022-07-20 22:09 UTC, creisle commented on ipr/content.spec.json
> +                            "expression (internal pancancer cohort)",
really i think we just need update the docs to accompany this change: https://bcgsc.github.io/pori/ipr/core_variants/expression/#comparators

perhaps we can add an exhaustive list of definitions for each of them here: https://bcgsc.github.io/pori/ipr/optional_analyses/comparators/

2022-07-20 22:10 UTC, creisle requested changes
update docs to add new comparator definition, how and when to use etc (technically this would be done in the other repo but i should be linked back to this PR)

2022-07-21 17:14 UTC, RaphaelPletz approved these changes

2022-07-21 17:15 UTC, merged